routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');



Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');


    Route::get('/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get('/titles/{id}', 'TitleController@index');
    Route::post('/titles/{id}', 'TitleController@post');


    Route::get('/cart', 'CartController@index')->name('cartindex');
    Route::post('/cart', 'CartController@store')->name('cartstore');
    Route::put('/cart', 'CartController@confirm')->name('cartconfirm');


    Route::get('/tyres/import', 'TyreController@index');
    Route::post('/tyres/import', 'TyreController@post');

    Route::get('/orders', 'OrderController@index')->name('orders');
    Route::get('/ordersadm', 'OrderController@ordersadm')->name('ordersadm');
    Route::post('/ordersadm', 'OrderController@update')->name('ordersupdate');

    Route::get('/products', 'ProductController@index')->name('products');
    Route::get('/productsadm', 'ProductAdmController@index')->name('productsadm');

    Route::get('/branch/products', 'ProductController@branches')->name('branchesproducts');

    Route::get('/branch/groups', 'GroupController@index')->name('groups');
    Route::get('/branch/groups/new', 'GroupController@newForm');
    Route::post('/branch/groups/new', 'GroupController@newFormSubmit');

    Route::get('/branch/groups/{id}', 'GroupController@editForm');
    Route::post('/branch/groups/{id}', 'GroupController@editFormSubmit');
    Route::get('/branch/groups/{id}/delete', 'GroupController@delete');

    Route::get('/branch/exchange', 'ExchangeController@index')->name('exchange');

    Route::get('/sales/import', 'SaleController@importform');
//    Route::post('/sales/import', 'SaleController@importpost');
    Route::post('/sales/import', 'SaleController@importFormSubmit');


    Route::get('/sales/{id}', 'SaleController@myOrgProducts');
    Route::get('/sales', 'SaleController@myOrgProducts')->name('sales');


    Route::get('/branch/containers', 'ContainerController@index')->name('containers');
    Route::get('/branch/containers/new', 'ContainerController@create');
    Route::post('/branch/containers/new', 'ContainerController@createPost');
    Route::get('/branch/containers/{id}', 'ContainerController@order');
    Route::post('/branch/containers/{id}', 'ContainerController@orderPost');


});



Route::middleware(['auth','admin_only'])->group(function () {

    Route::resource('/users', 'UserController');
    Route::resource('/orgs', 'OrgController');
    Route::resource('/margins', 'MarginController');
//    Route::get('/importlog', 'ImportLogController@index');

    Route::get('/admin/topmanager', 'SaleController@topmanager')->name('topmanager');

    Route::get('/admin/login_as/{id}', 'UserController@login_as');

    Route::get('/admin/ref', 'TitleController@ref');
    Route::post('/admin/ref', 'TitleController@refpost');

      // TODO: переделать на resource

    Route::get('/branch/containers/{id}/edit', 'ContainerController@edit');
    Route::post('/branch/containers/{id}/edit', 'ContainerController@editPost');
    Route::delete('/branch/containers/{id}', 'ContainerController@delete');



});

app/Margin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Margin extends Model
{
	use SoftDeletes;

	protected $guarded = [];

	public function users()
	{
		return $this->hasMany('App\User');
	}

	public function getProcentAttribute()
	{
		if ($this->margin > 1){
			$p = '+'.($this->margin-1)*100;
		 }
			else{
				$p ='-'.(1-$this->margin)*100;
			}
			return $p.'%';
	}
}

app/Http/Controllers/MarginController.php
<?php

namespace App\Http\Controllers;

use App\Org;
use App\User;
use Illuminate\Http\Request;
use App\Margin;
use Session;

class MarginController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $margins = Margin::orderBy('margin')->get();
        return view('margins/index', ['margins' => $margins]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('margins/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
             'title' => 'unique:margins|required|min:5',
         ]);

        $input = $request->all();

        Margin::create($input);
        Session::flash('flash_message', "Наценка &laquo;$request->title&raquo; создана!");

        return redirect()->route('margins.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $margin = Margin::findOrFail($id);
        return view('margins.edit', ['margin'=>$margin]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $margin = Margin::findOrFail($id);
        return view('margins.edit', ['margin'=>$margin]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $margin = Margin::findOrFail($id);

        $this->validate($request, [
            'title' => 'required|min:5'
        ]);

        $input = $request->all();
        $margin->fill($input);

        $margin->save();

        Session::flash('flash_message', "Редактирование &laquo;$margin->title&raquo; произведено успешно");

        return redirect()->route('margins.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $margin = Margin::findOrFail($id);

        $margin->delete();

        Session::flash('flash_message', "Наценка $margin->title удалена!");

        return redirect()->route('margins.index');
    }
}

resources/views/margins/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

@include('_partials.errors')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Новая наценка</h3></div>

                <div class="panel-body">

{!! Form::open(array('route' => 'margins.store','method'=>'POST')) !!}
<div class="form-group">
  <strong>Название</strong>
  {!! Form::text('title', null, array('placeholder' => 'Название','class' => 'form-control','required' => 'required')) !!}
 </div>

<div class="form-group">
    <strong>Процент</strong>
    {!! Form::text('margin', null, array('placeholder' => 'Наценка','class' => 'form-control','required' => 'required','step'=>"0.01",'min'=>'0.5','max'=>'5')) !!}
</div>

{!! Form::submit('Добавить', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
  </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/margins/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

  @if (count($errors) > 0)
      <div class="alert alert-danger">
          <strong>Ошибка!</strong><br><br>
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
  @endif

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Редактировать наценки</h3></div>

                <div class="panel-body">


{!! Form::model($margin, [
    'method' => 'PATCH',
    'route' => ['margins.update', $margin->id]
]) !!}



<div class="form-group">
  <strong>Название</strong>
  {!! Form::text('title', null, array('placeholder' => 'Название','class' => 'form-control')) !!}
 </div>

  <div class="form-group">
    <strong>Коэффициент</strong>
     {!! Form::number('margin', null, array('placeholder' => 'процент','class' => 'form-control','step'=>"0.01",'min'=>'0.5','max'=>'5')) !!}
  </div>

<div class="row">

  <div class="col-md-6 text-left">
{!! Form::submit('Редактировать', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
</div>


  <div class="col-md-6 text-right">
         {!! Form::open([
             'method' => 'DELETE',
             'route' => ['margins.destroy', $margin->id],

         ]) !!}

    <input type="submit" value="Удалить" class="btn btn-danger" onclick="return confirm('Удалить наценку &laquo;{{ $margin->title }}&raquo;?')">

         {!! Form::close() !!}
     </div>


</div>



  </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/margins/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif


              <div class="panel panel-default">
                  <div class="panel-heading"><h3 class="panel-title">Наценки и скидки</h3></div>


        <div class="panel-body">
          <a href="/margins/create" class="btn btn-success btn-sm">Новая наценка</a>
        </div>

        <table class="table table-hover">

          @foreach ($margins as $margin)
            <tr>
              <td>
                <a href="{{ route('margins.edit', $margin->id) }}">
                <b>{{ $margin->title }}</b>
              </a>
                <br>
                   {{-- {{ $margin->margin }} --}}



              </td>
              <td>
      {{  $margin->procent }}
            </td>
              <td>
                <div class="btn-group btn-group-sm pull-right" role="group">

                </div>
              </td>
            </tr>

          @endforeach


        </table>

      </div>
    </div>
  </div>
</div>
@endsection