routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//$this->get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//$this->post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');



Route::middleware(['auth'])->group(function () {

    Route::get('/home', 'HomeController@index')->name('home');


    Route::get('/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get('/titles/{id}', 'TitleController@index');
    Route::post('/titles/{id}', 'TitleController@post');


    Route::get('/cart', 'CartController@index')->name('cartindex');
    Route::post('/cart', 'CartController@store')->name('cartstore');
    Route::put('/cart', 'CartController@confirm')->name('cartconfirm');


    Route::get('/tyres/import', 'TyreController@index');
    Route::post('/tyres/import', 'TyreController@post');

    Route::get('/orders', 'OrderController@index')->name('orders');
    Route::get('/ordersadm', 'OrderController@ordersadm')->name('ordersadm');
    Route::post('/ordersadm', 'OrderController@update')->name('ordersupdate');

    Route::get('/products', 'ProductController@index')->name('products');
    Route::get('/productsadm', 'ProductAdmController@index')->name('productsadm');

    Route::get('/branch/products', 'ProductController@branches')->name('branchesproducts');

    Route::get('/branch/groups', 'GroupController@index')->name('groups');
    Route::get('/branch/groups/new', 'GroupController@newForm');
    Route::post('/branch/groups/new', 'GroupController@newFormSubmit');

    Route::get('/branch/groups/{id}', 'GroupController@editForm');
    Route::post('/branch/groups/{id}', 'GroupController@editFormSubmit');
    Route::get('/branch/groups/{id}/delete', 'GroupController@delete');

    Route::get('/branch/exchange', 'ExchangeController@index')->name('exchange');

    Route::get('/sales/import', 'SaleController@importform');
//    Route::post('/sales/import', 'SaleController@importpost');
    Route::post('/sales/import', 'SaleController@importFormSubmit');


    Route::get('/sales/{id}', 'SaleController@myOrgProducts');
    Route::get('/sales', 'SaleController@myOrgProducts')->name('sales');


    Route::get('/branch/containers', 'ContainerController@index')->name('containers');
    Route::get('/branch/containers/new', 'ContainerController@create');
    Route::post('/branch/containers/new', 'ContainerController@createPost');
    Route::get('/branch/containers/{id}', 'ContainerController@order');
    Route::post('/branch/containers/{id}', 'ContainerController@orderPost');


});



Route::middleware(['auth','admin_only'])->group(function () {

    Route::resource('/users', 'UserController');
    Route::resource('/orgs', 'OrgController');
    Route::resource('/margins', 'MarginController');
//    Route::get('/importlog', 'ImportLogController@index');

    Route::get('/admin/topmanager', 'SaleController@topmanager')->name('topmanager');

    Route::get('/admin/login_as/{id}', 'UserController@login_as');

    Route::get('/admin/ref', 'TitleController@ref');
    Route::post('/admin/ref', 'TitleController@refpost');

      // TODO: переделать на resource

    Route::get('/branch/containers/{id}/edit', 'ContainerController@edit');
    Route::post('/branch/containers/{id}/edit', 'ContainerController@editPost');
    Route::delete('/branch/containers/{id}', 'ContainerController@delete');



});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
  protected $fillable = ['info', 'status_id','user_id'];

  public function user()
  {
      return $this->belongsTo('App\User');
  }

  public function status()
  {
      return $this->belongsTo('App\Status');
  }

  public function products()
  {
      return $this->belongsToMany('App\Product')->withPivot('num', 'price');
  }

}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;


class Product extends Model
{
	use SoftDeletes;



protected $fillable = ['title','title_key','price','category_id',
    'stock1','stock2','stock3',
    'price1','price2','price3',
    'sales1','sales2','sales3'
    ];

    private $import_months = 3; // за сколько месяцев сделан анализ продаж из 1С (в файле импорта)
    private $reserve_months = 2; // на сколько месяцев нужен резерв

    ///////////////////////////

    public function groups()
    {
        return $this->belongsToMany('App\Group');
    }


  public function category()
  {
    return $this->belongsTo('App\Category');
  }

  public function orders()
  {
    return $this->belongsToMany('App\Order');
  }

  public function containers()
    {
        return $this->belongsToMany('App\Container')->withPivot('org1', 'org2','org3');
    }
///////////////////////



    public function getAvgAttribute($value='') // средние продажи за 1мес
    {
        $return = $this->my_org_sales /  $this->import_months;
        $return = round($return);
        return $return;
    }

//    public function getAvg1Attribute($value='') // средние продажи за 1мес РОСТОВ
//    {
//        $return = $this->sales1 /  $this->import_months;
//        $return = round($return);
//        return $return;
//    }

    public function avg1() // средние продажи за 1мес
    {
        $return = $this->sales1 /  $this->import_months;
        $return = round($return);
        return $return;
    }

    public function avg2() // средние продажи за 1мес СПб
    {
        $return = $this->sales2 /  $this->import_months;
        $return = round($return);
        return $return;
    }

    public function avg3() // средние продажи за 1мес Мск
    {
        $return = $this->sales3 /  $this->import_months;
        $return = round($return);
        return $return;
    }

////////////// необходимый резерв, на 2 мес

    public function getReserveAttribute($value='') // необходимый резерв, на 2 мес
    {
        $return = $this->avg * $this->reserve_months;
        $return = round($return);
        return $return;
    }

    public function reserve1() //  РОСТОВ
    {
        $return = $this->avg1() * $this->reserve_months;
        $return = round($return);
        return $return;
    }

    public function reserve2() //  СПб
    {
        $return = $this->avg2() * $this->reserve_months;
        $return = round($return);
        return $return;
    }

    public function reserve3() //  Мск
    {
        $return = $this->avg3() * $this->reserve_months;
        $return = round($return);
        return $return;
    }

//////////избыток на складе, шт
    public function getOverageItemsAttribute($value='') // избыток на складе, шт
    {
        // остатки минус резерв
        $return = $this->my_org_stock - $this->reserve;
        $return = round($return);
        return $return;
    }

    public function getOverageItems1Attribute($value='') // избыток на складе, шт
    {
        // остатки минус резерв
        $return = $this->stock1 - $this->reserve1();
        $return = round($return);
        return $return;
    }

    public function getOverageItems2Attribute($value='') // избыток на складе, шт
    {
        // остатки минус резерв
        $return = $this->stock2 - $this->reserve2();
        $return = round($return);
        return $return;
    }

    public function getOverageItems3Attribute($value='') // избыток на складе, шт
    {
        // остатки минус резерв
        $return = $this->stock3 - $this->reserve3();
        $return = round($return);
        return $return;
    }


    public function getOverageRub1Attribute($value='')
    {
        $return = ($this->stock1 - $this->reserve1())*$this->price1;
          return $return;
    }

    public function getOverageRub2Attribute($value='')
    {
        $return = ($this->stock2 - $this->reserve2())*$this->price2;
          return $return;
    }

    public function getOverageRub3Attribute($value='')
    {
        $return = ($this->stock3 - $this->reserve3())*$this->price3;
        return $return;
    }

//    public function overageItems1() // избыток на складе, шт РОСТОВ
//    {
//        // остатки минус резерв
//        $return = $this->stock1 - $this->reserve1();
//        $return = round($return);
//        return $return;
//    }
//
//    public function overageItems2() // избыток на складе, шт СПб
//    {
//        // остатки минус резерв
//        $return = $this->stock2 - $this->reserve2();
//        $return = round($return);
//        return $return;
//    }
//
//    public function overageItems3() // избыток на складе, шт Мск
//    {
//        // остатки минус резерв
//        $return = $this->stock3 - $this->reserve3();
//        $return = round($return);
//        return $return;
//    }
    public function getTotalRub1Attribute()
    {
        return $this->stock1*$this->price1;
    }

    public function getTotalRub2Attribute()
    {
        return $this->stock2*$this->price2;
    }

    public function getTotalRub3Attribute()
    {
        return $this->stock3*$this->price3;
    }



    public function getOverageRubAttribute($value='') // избыток на складе, сумма
    {
        // избыток умножить на себестоимость
        $return = $this->overage_items * $this->my_org_price;
        $return = round($return);
        return $return;
    }



    public function getMyOrgSalesAttribute()
    {
    $org_id = \Auth::user()->org_id;
    switch ($org_id){
        case 1:
            return $this->sales1;
            break;
        case 2:
            return $this->sales2;
            break;
        case 3:
            return $this->sales3;
            break;
    }
    }

    public function getMyOrgStockAttribute()
    {
        $org_id = \Auth::user()->org_id;
        switch ($org_id){
            case 1:
                return $this->stock1;
                break;
            case 2:
                return $this->stock2;
                break;
            case 3:
                return $this->stock3;
                break;
        }
    }

    public function getMyOrgPriceAttribute()
    {
        $org_id = \Auth::user()->org_id;
        switch ($org_id){
            case 1:
                return $this->price1;
                break;
            case 2:
                return $this->price2;
                break;
            case 3:
                return $this->price3;
                break;
        }
    }

public function getOrdersumAttribute($value='')
{
	$return = $this->pivot->num * $this->pivot->price;
	return $return;
}



	// массив, цены для всех наценок
	public function getPricesAttribute($value='')
	{
	$margins = DB::table('margins')->pluck('margin', 'id')->all();

		foreach ($margins	as $key => $margin) {
		$usd = $this->price * $margin; // цена для каждого уровня
		$r[$key] = round($usd * \App\Dollar::lastRate()->rub_rate,-2); //умножаем на свежий курс, округляем
		}
		return $r;
	}

	// массив, персональная цена, с учетом скидки/наценки текущего юзера
	public function getMyPriceAttribute()
	{

		$usd = $this->price * \Auth::user()->margin->margin; // цена для текущего юзера
		$r = round($usd * \App\Dollar::lastRate()->rub_rate, -2); //умножаем на свежий курс, округляем

		return $r;
	}




}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Status;
use Session;
use Illuminate\Http\Request;

class OrderController extends Controller
{
  public function index(Request $request)
  {
      $orders = Order::where('user_id', $request->user()->id)->orderBy('updated_at','desc')->get();
      return view('orders/index', ['orders' => $orders]);
  }
  public function ordersadm(Request $request)
  {
    $statuses = Status::pluck('status','id');
      //  $margins = \App\Margin::pluck('title','id');
      $orders = Order::orderBy('updated_at','desc')->get();
      return view('orders/admin', ['orders' => $orders,'statuses'=>$statuses]);
  }

public function update(Request $request)
{
//   $i = $request->query->all();
// dd($i);
  Order::find($request->order_id)->update(['status_id' => $request->status_id]);

  Session::flash('flash_message', "Статус заявки №$request->order_id изменен!");

 return redirect()->route('ordersadm');

}


}

resources/views/orders/admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif

<h3>Все заявки</h3>

  @foreach ($orders as $order)
              <div class="panel panel-default">
                  <div class="panel-heading"><b>{{ $order->user->name }}</b> <br>
                    Заявка №{{ $order->id }} от {{ $order->created_at->toDateString() }}
<span class="pull-right label label-status{{$order->status->id}}">{{$order->status->status}}</span>
                  </div>


        {{-- <div class="panel-body">       </div> --}}

        <table class="table table-hover">

      {{-- @dd($order->orderproduct)     --}}
  @foreach ($order->products as $product)
              <tr>
                <td>{{ $product->title }}
                </td>
                <td>{{ $product->pivot->num }} * {{ $product->pivot->price }}&thinsp;&#8381;
              </td>
                <td>{{ $product->ordersum }}&thinsp;&#8381;
                </td>
              </tr>
  @endforeach
  <tfoot><td>
    {!! Form::model($order, [
        'method' => 'POST',
        'route' => ['ordersupdate']
    ]) !!}
    <input type="hidden" name="order_id" value="{{$order->id}}">
       {{ Form::select('status_id', $statuses, $order->status_id,['class' => 'form-control input-sm','style'=>'width:12em;display:inline-block']) }}
       <button class="btn btn-primary btn-xs" type="submit" name="button">Изменить статус</button>
    {{-- {!! Form::submit('Редактировать', ['class' => 'btn btn-primary']) !!} --}}
    {!! Form::close() !!}


  </td>
    <td>Итого        </td>
    <td><b>{{$order->products->sum('ordersum')}}</b>&thinsp;&#8381;</td>
  </tfoot>
        </table>


      </div>

@endforeach
    </div>
  </div>
</div>
@endsection

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif

{{-- <h3>Заявки</h3> --}}

  @foreach ($orders as $order)
              <div class="panel panel-default">
                  <div class="panel-heading"><h3 class="panel-title">Заявка №{{$order->id}}</h3>
                    от {{$order->created_at->toDateString() }}
<span class="pull-right label label-status{{$order->status->id}}">{{$order->status->status}}</span>
                  </div>


        {{-- <div class="panel-body">       </div> --}}

        <table class="table table-hover">

      {{-- @dd($order->orderproduct)     --}}
  @foreach ($order->products as $product)
              <tr>
                <td>{{ $product->title }}
                </td>
                <td>{{ $product->pivot->num }} * {{ $product->pivot->price }}&thinsp;&#8381;
              </td>
                <td>{{ $product->ordersum }}&thinsp;&#8381;
                </td>
              </tr>
  @endforeach
  <tfoot><td></td>
    <td>Итого        </td>
    <td><b>{{$order->products->sum('ordersum')}}</b>&thinsp;&#8381;</td>
  </tfoot>
        </table>


      </div>

@endforeach
    </div>
  </div>
</div>
@endsection